<!-- BEGIN KEY -->
public class java.lang.RuntimeException extends java.lang.Exception
<!-- END KEY -->
<!-- BEGIN DATA -->
 <code>RuntimeException</code> is the superclass of those 
 exceptions that can be thrown during the normal operation of the 
 Java Virtual Machine. 
 <p>
 A method is not required to declare in its <code>throws</code> 
 clause any subclasses of <code>RuntimeException</code> that might 
 be thrown during the execution of the method but not caught. 


 @author  Frank Yellin
 @version 1.14, 11/17/05
 @since   JDK1.0

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.RuntimeException()
<!-- END KEY -->
<!-- BEGIN DATA -->
Constructs a new runtime exception with <code>null</code> as its
 detail message.  The cause is not initialized, and may subsequently be
 initialized by a call to {@link #initCause}.

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.RuntimeException(String message)
<!-- END KEY -->
<!-- BEGIN DATA -->
Constructs a new runtime exception with the specified detail message.
 The cause is not initialized, and may subsequently be initialized by a
 call to {@link #initCause}.

 @param   message   the detail message. The detail message is saved for 
          later retrieval by the {@link #getMessage()} method.

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.RuntimeException(String message, Throwable cause)
<!-- END KEY -->
<!-- BEGIN DATA -->
 Constructs a new runtime exception with the specified detail message and
 cause.  <p>Note that the detail message associated with
 <code>cause</code> is <i>not</i> automatically incorporated in
 this runtime exception's detail message.

 @param  message the detail message (which is saved for later retrieval
         by the {@link #getMessage()} method).
 @param  cause the cause (which is saved for later retrieval by the
         {@link #getCause()} method).  (A <tt>null</tt> value is
         permitted, and indicates that the cause is nonexistent or
         unknown.)
 @since  1.4

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.RuntimeException(Throwable cause)
<!-- END KEY -->
<!-- BEGIN DATA -->
Constructs a new runtime exception with the specified cause and a
 detail message of <tt>(cause==null ? null : cause.toString())</tt>
 (which typically contains the class and detail message of
 <tt>cause</tt>).  This constructor is useful for runtime exceptions
 that are little more than wrappers for other throwables.

 @param  cause the cause (which is saved for later retrieval by the
         {@link #getCause()} method).  (A <tt>null</tt> value is
         permitted, and indicates that the cause is nonexistent or
         unknown.)
 @since  1.4

<!-- END DATA -->
