<!-- BEGIN KEY -->
public class javax.transaction.xa.XAException extends java.lang.Exception
<!-- END KEY -->
<!-- BEGIN DATA -->
 The XAException is thrown by the Resource Manager (RM) to inform the 
 Transaction Manager of an error encountered by the involved transaction.


<!-- END DATA -->
<!-- BEGIN KEY -->
public int javax.transaction.xa.XAException.errorCode
<!-- END KEY -->
<!-- BEGIN DATA -->
 The error code with which to create the SystemException.

 @serial The error code for the exception

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBBASE
<!-- END KEY -->
<!-- BEGIN DATA -->
 The inclusive lower bound of the rollback codes.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBROLLBACK
<!-- END KEY -->
<!-- BEGIN DATA -->
 Indicates that the rollback was caused by an unspecified reason.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBCOMMFAIL
<!-- END KEY -->
<!-- BEGIN DATA -->
 Indicates that the rollback was caused by a communication failure.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBDEADLOCK
<!-- END KEY -->
<!-- BEGIN DATA -->
 A deadlock was detected.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBINTEGRITY
<!-- END KEY -->
<!-- BEGIN DATA -->
 A condition that violates the integrity of the resource was detected.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBOTHER
<!-- END KEY -->
<!-- BEGIN DATA -->
 The resource manager rolled back the transaction branch for a reason
 not on this list.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBPROTO
<!-- END KEY -->
<!-- BEGIN DATA -->
 A protocol error occurred in the resource manager.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBTIMEOUT
<!-- END KEY -->
<!-- BEGIN DATA -->
 A transaction branch took too long.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBTRANSIENT
<!-- END KEY -->
<!-- BEGIN DATA -->
 May retry the transaction branch.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBEND
<!-- END KEY -->
<!-- BEGIN DATA -->
 The inclusive upper bound of the rollback error code.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_NOMIGRATE
<!-- END KEY -->
<!-- BEGIN DATA -->
 Resumption must occur where the suspension occurred.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_HEURHAZ
<!-- END KEY -->
<!-- BEGIN DATA -->
 The transaction branch may have been heuristically completed.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_HEURCOM
<!-- END KEY -->
<!-- BEGIN DATA -->
 The transaction branch has been heuristically committed.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_HEURRB
<!-- END KEY -->
<!-- BEGIN DATA -->
 The transaction branch has been heuristically rolled back.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_HEURMIX
<!-- END KEY -->
<!-- BEGIN DATA -->
 The transaction branch has been heuristically committed and 
 rolled back.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RETRY
<!-- END KEY -->
<!-- BEGIN DATA -->
 Routine returned with no effect and may be reissued.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RDONLY
<!-- END KEY -->
<!-- BEGIN DATA -->
 The transaction branch was read-only and has been committed.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_ASYNC
<!-- END KEY -->
<!-- BEGIN DATA -->
 There is an asynchronous operation already outstanding.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_RMERR
<!-- END KEY -->
<!-- BEGIN DATA -->
 A resource manager error has occurred in the transaction branch.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_NOTA
<!-- END KEY -->
<!-- BEGIN DATA -->
 The XID is not valid.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_INVAL
<!-- END KEY -->
<!-- BEGIN DATA -->
 Invalid arguments were given.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_PROTO
<!-- END KEY -->
<!-- BEGIN DATA -->
 Routine was invoked in an inproper context.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_RMFAIL
<!-- END KEY -->
<!-- BEGIN DATA -->
 Resource manager is unavailable.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_DUPID
<!-- END KEY -->
<!-- BEGIN DATA -->
 The XID already exists.

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_OUTSIDE
<!-- END KEY -->
<!-- BEGIN DATA -->
 The resource manager is doing work outside a global transaction.

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.transaction.xa.XAException()
<!-- END KEY -->
<!-- BEGIN DATA -->
 Create an XAException.

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.transaction.xa.XAException(String s)
<!-- END KEY -->
<!-- BEGIN DATA -->
 Create an XAException with a given string.

 @param s The <code>String</code> object containing the exception
		message.

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.transaction.xa.XAException(int errcode)
<!-- END KEY -->
<!-- BEGIN DATA -->
 Create an XAException with a given error code.

 @param errcode The error code identifying the exception.

<!-- END DATA -->
