<!-- BEGIN KEY -->
public class javax.naming.LimitExceededException extends javax.naming.NamingException
<!-- END KEY -->
<!-- BEGIN DATA -->
当某一方法因为用户或系统指定的限制而异常终止时，抛出此异常。此异常与 InsufficientResourceException 的不同之处在于，LimitExceededException 是因为用户/系统指定的限制而抛出的。例如，为完成请求而耗尽内存是资源不足异常。客户端请求 10 个答案却得到 11 个答案则是大小限制异常。
<p>
这些限制的示例包括客户端和服务器配置限制，比如大小、时间、跳数，等等。
 <p>
应用于 NamingException 的同步和序列化问题在这里可以直接应用。

@author Rosanna Lee
@author Scott Seligman
@version 1.8 05/11/17
@since 1.3

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.LimitExceededException()
<!-- END KEY -->
<!-- BEGIN DATA -->
构造一个新的 LimitExceededException 实例，将解释和所有名称解析字段初始化为 null。

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.LimitExceededException(String explanation)
<!-- END KEY -->
<!-- BEGIN DATA -->
使用解释构造一个新的 LimitExceededException 实例。其他所有字段都默认为 null。
@param explanation 有关此异常的可能为 null 的详细信息。
@see java.lang.Throwable#getMessage

<!-- END DATA -->
