<!-- BEGIN KEY -->
public class javax.naming.NotContextException extends javax.naming.NamingException
<!-- END KEY -->
<!-- BEGIN DATA -->
当命名操作进行到需要上下文来继续该操作的某处，而解析的对象不是一个上下文时，抛出此异常。例如，Context.destroy() 要求指定的对象是一个上下文。如果不是，则抛出 NotContextException。另一个示例是 Context 方法在解析阶段期间遇到的非上下文。
<p>
当需要特定子类型的上下文（比如 DirContext），解析的对象是一个上下文，但不属于所需的子类型时，也会抛出此异常。
 <p>
应用于 NamingException 的同步和序列化问题在这里可以直接应用。
@see Context#destroySubcontext

@author Rosanna Lee
@author Scott Seligman
@version 1.8 05/11/17
@since 1.3

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.NotContextException(String explanation)
<!-- END KEY -->
<!-- BEGIN DATA -->
使用解释构造一个新的 NotContextException 实例。其他所有字段都默认为 null。

@param	explanation	有关此异常的附加详细信息（可能为 null）。
@see java.lang.Throwable#getMessage

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.NotContextException()
<!-- END KEY -->
<!-- BEGIN DATA -->
构造一个新的 NotContextException 实例。所有字段都默认为 null。

<!-- END DATA -->
