<!-- BEGIN KEY -->
public class java.sql.SQLRuntimeException extends java.lang.RuntimeException
<!-- END KEY -->
<!-- BEGIN DATA -->
 The subclass of {@link RuntimeException} which is thrown by 
 the ease of development APIs, such as <code>DataSet</code>.
  
 @since 1.6

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.sql.SQLRuntimeException(String reason)
<!-- END KEY -->
<!-- BEGIN DATA -->
  Constructs a <code>SQLRuntimeException</code> object with a given
 <code>reason</code>. 

 The <code>cause</code> is not initialized, and may subsequently be
 initialized by a call to the 
 {@link Throwable#initCause(java.lang.Throwable)} method.
 <p>
 @param reason a description of the exception 

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.sql.SQLRuntimeException(Throwable cause)
<!-- END KEY -->
<!-- BEGIN DATA -->
  Constructs a <code>SQLRuntimeException</code> object with a given
 <code>cause</code>.
 The <code>reason</code>  is initialized to <code>null</code> if 
 <code>cause==null</code> or to <code>cause.toString()</code> if 
 <code>cause!=null</code>.
 <p>
 @param cause the underlying reason for this <code>SQLRuntimeException</code> 
 (which is saved for later retrieval by the <code>getCause()</code> method); 
 may be null indicating the cause is non-existent or unknown.
 @since 1.6

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.sql.SQLRuntimeException(String reason, Throwable cause)
<!-- END KEY -->
<!-- BEGIN DATA -->
 Constructs a <code>SQLRuntimeException</code> object with a given
 <code>reason</code> and  <code>cause</code>.  
 @param reason a description of the exception. 
 @param cause the underlying reason for this <code>SQLRuntimeException</code> 
 (which is saved for later retrieval by the <code>getCause()</code> method); 
 may be null indicating the cause is non-existent or unknown.
 @since 1.6

<!-- END DATA -->
