<!-- BEGIN KEY -->
public class javax.naming.directory.AttributeInUseException extends javax.naming.NamingException
<!-- END KEY -->
<!-- BEGIN DATA -->
当操作试图添加已经存在的属性时抛出此异常。
 <p>
应用于 NamingException 的同步和序列化问题在这里可以直接应用。

@author Rosanna Lee
@author Scott Seligman
@version 1.8 05/11/17

@see DirContext#modifyAttributes
@since 1.3

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.directory.AttributeInUseException(String explanation)
<!-- END KEY -->
<!-- BEGIN DATA -->
使用解释构造一个新的 AttributeInUseException 实例。将所有其他字段都设置为 null。

@param	explanation	有关此异常的可能为 null 的附加详细信息。
@see java.lang.Throwable#getMessage

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.directory.AttributeInUseException()
<!-- END KEY -->
<!-- BEGIN DATA -->
构造一个新的 AttributeInUseException 实例。所有字段都被初始化为 null。

<!-- END DATA -->
