<!-- BEGIN KEY -->
public class javax.management.RuntimeOperationsException extends javax.management.JMRuntimeException
<!-- END KEY -->
<!-- BEGIN DATA -->
表示在 MBean 上执行操作时代理中抛出的运行时异常。它包装抛出的实际 <CODE>java.lang.RuntimeException</CODE>。
	
@since 1.5

<!-- END DATA -->
<!-- BEGIN KEY -->
private java.lang.RuntimeException javax.management.RuntimeOperationsException.runtimeException
<!-- END KEY -->
<!-- BEGIN DATA -->
@serial 封装的 {@link RuntimeException}

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.RuntimeOperationsException(RuntimeException e)
<!-- END KEY -->
<!-- BEGIN DATA -->
创建包装实际 <CODE>java.lang.RuntimeException</CODE> 的 <CODE>RuntimeOperationsException</CODE>。

@param e 包装的异常。

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.RuntimeOperationsException(RuntimeException e, String message)
<!-- END KEY -->
<!-- BEGIN DATA -->
创建包装带有详细信息的实际 <CODE>java.lang.RuntimeException</CODE> 的 <CODE>RuntimeOperationsException</CODE>。

@param e 包装的异常。
@param message 详细消息。

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.RuntimeException javax.management.RuntimeOperationsException.getTargetException()
<!-- END KEY -->
<!-- BEGIN DATA -->
返回抛出的实际 {@link RuntimeException}。

@return 包装的 {@link RuntimeException}。

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.Throwable javax.management.RuntimeOperationsException.getCause()
<!-- END KEY -->
<!-- BEGIN DATA -->
返回抛出的实际 {@link RuntimeException}。

@return 包装的 {@link RuntimeException}。

<!-- END DATA -->
