<!-- BEGIN KEY -->
public class java.security.cert.CertificateException extends java.security.GeneralSecurityException
<!-- END KEY -->
<!-- BEGIN DATA -->
此异常指示各种证书问题中的一种。

@author Hemma Prafullchandra
@version 1.33
@see Certificate

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.security.cert.CertificateException()
<!-- END KEY -->
<!-- BEGIN DATA -->
构造不带详细消息的 Certificate 异常。详细消息是描述此特定异常的字符串。 

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.security.cert.CertificateException(String msg)
<!-- END KEY -->
<!-- BEGIN DATA -->
构造带给定详细消息的 Certificate 异常。详细消息是描述此特定异常的字符串。

@param msg 详细消息。  

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.security.cert.CertificateException(String message, Throwable cause)
<!-- END KEY -->
<!-- BEGIN DATA -->
创建带指定详细消息和原因的 <code>CertificateException</code>。

@param message 详细消息（保存此消息，以便以后通过 {@link #getMessage()} 方法获取它）。
@param cause 原因（保存此原因，以便以后通过 {@link #getCause()} 方法获取它）。（允许使用 <tt>null</tt> 值，指出原因是不存在的或是未知的。）
@since 1.5

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.security.cert.CertificateException(Throwable cause)
<!-- END KEY -->
<!-- BEGIN DATA -->
创建带指定原因和详细消息的 <code>CertificateException</code>，详细消息是 <tt>(cause==null ? null :cause.toString())</tt>（它通常包含 <tt>cause</tt> 的类和详细消息）。

@param cause 原因（保存此原因，以便以后通过 {@link #getCause()} 方法获取它）。（允许使用 <tt>null</tt> 值，指出原因是不存在的或是未知的。）
@since 1.5

<!-- END DATA -->
