<!-- BEGIN KEY -->
public class javax.security.auth.DestroyFailedException extends java.lang.Exception
<!-- END KEY -->
<!-- BEGIN DATA -->
当 <code>destroy</code> 操作失败时，抛出此异常。
 
<p> 此异常由实现 <code>Destroyable</code> 接口的证书在 <code>destroy</code> 方法失败时抛出。

@version 1.8, 12/19/03

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.security.auth.DestroyFailedException()
<!-- END KEY -->
<!-- BEGIN DATA -->
构造不带详细消息的 DestroyFailedException。详细消息是描述此特定异常的字符串。

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.security.auth.DestroyFailedException(String msg)
<!-- END KEY -->
<!-- BEGIN DATA -->
构造带指定详细消息的 DestroyFailedException。详细消息是描述此特定异常的字符串。

 <p>

@param msg 详细消息。  

<!-- END DATA -->
