<!-- BEGIN KEY -->
public class javax.naming.directory.AttributeInUseException extends javax.naming.NamingException
<!-- END KEY -->
<!-- BEGIN DATA -->
 This exception is thrown when an operation attempts
 to add an attribute that already exists.
 <p>
 Synchronization and serialization issues that apply to NamingException
 apply directly here.

 @author Rosanna Lee
 @author Scott Seligman
 @version 1.8 05/11/17

 @see DirContext#modifyAttributes
 @since 1.3

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.directory.AttributeInUseException(String explanation)
<!-- END KEY -->
<!-- BEGIN DATA -->
 Constructs a new instance of AttributeInUseException with
 an explanation. All other fields are set to null.

 @param	explanation	Possibly null additional detail about this exception.
 @see java.lang.Throwable#getMessage

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.naming.directory.AttributeInUseException()
<!-- END KEY -->
<!-- BEGIN DATA -->
 Constructs a new instance of AttributeInUseException.
 All fields are initialized to null.

<!-- END DATA -->
