<!-- BEGIN KEY -->
public class java.lang.ExceptionInInitializerError extends java.lang.LinkageError
<!-- END KEY -->
<!-- BEGIN DATA -->
静态初始化程序中发生意外异常的信号。抛出 <code>ExceptionInInitializerError</code> 表明在计算静态初始值或静态变量的初始值期间发生异常。

<p>从版本 1.4 开始，这个异常已经更新过，符合通用异常链机制。&ldquo;保存的 throwable 对象&rdquo;可能是在构造的时候提供的，并且可以通过 {@link #getException()} 方法来访问，这类对象目前被认为是导致异常的<i>原因</i>，可以通过 {@link Throwable#getCause()} 方法以及前面提到的&ldquo;遗留方法&rdquo;访问它。


@author  Frank Yellin 
@version 1.17, 12/19/03 
@since   JDK1.1

<!-- END DATA -->
<!-- BEGIN KEY -->
private java.lang.Throwable java.lang.ExceptionInInitializerError.exception
<!-- END KEY -->
<!-- BEGIN DATA -->
如果使用 ExceptionInInitializerError(Throwable thrown) 构造方法来实例化此对象，则该字段将保持异常
 
@serial 
 

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.ExceptionInInitializerError()
<!-- END KEY -->
<!-- BEGIN DATA -->
构造一个 <code>ExceptionInInitializerError</code>，使用 <code>null</code> 作为其详细消息字符串，并且不使用任何保存的 throwable 对象。详细消息是描述这个特定异常的 String。

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.ExceptionInInitializerError(Throwable thrown)
<!-- END KEY -->
<!-- BEGIN DATA -->
保存对抛出的 <code>Throwable</code> 对象的引用，以便以后通过 {@link #getException()} 方法对其进行获取，通过这种方式构造一个新的 <code>ExceptionInInitializerError</code> 类。 详细消息字符串被设置为 <code>null</code>。

@param thrown 抛出的异常

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.ExceptionInInitializerError(String s)
<!-- END KEY -->
<!-- BEGIN DATA -->
构造带指定详细消息的 ExceptionInInitializerError。详细消息是描述这个特定异常的 String。保存这个详细消息字符串，以便以后通过 {@link Throwable#getMessage()} 方法对其进行获取。没有任何保存的 throwable 对象。 


@param s 详细消息

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.Throwable java.lang.ExceptionInInitializerError.getException()
<!-- END KEY -->
<!-- BEGIN DATA -->
返回静态初始化期间发生的异常，该异常导致发生此错误。

<p>该方法早于通用异常链设施。 {@link Throwable#getCause()} 方法现在首先被用来获得该信息。
 
@return 此 <code>ExceptionInInitializerError</code> 的已保存的 throwable 对象；如果此 <code>ExceptionInInitializerError</code> 没有任何已保存的 throwable 对象，则返回 <code>null</code>。 

<!-- END DATA -->
<!-- BEGIN KEY -->
public java.lang.Throwable java.lang.ExceptionInInitializerError.getCause()
<!-- END KEY -->
<!-- BEGIN DATA -->
返回导致该错误的原因（导致发生此错误的静态初始化期间发生的异常）。
 
@return 造成该错误的原因；如果原因不存在或是未知的，则返回 <code>null</code>。
@since   1.4

<!-- END DATA -->
