<!-- BEGIN KEY -->
public class javax.management.remote.JMXProviderException extends java.io.IOException
<!-- END KEY -->
<!-- BEGIN DATA -->
 <p>Exception thrown by {@link JMXConnectorFactory} and
 {@link JMXConnectorServerFactory} when a provider exists for
 the required protocol but cannot be used for some reason.</p>

 @see JMXConnectorFactory#newJMXConnector
 @see JMXConnectorServerFactory#newJMXConnectorServer
 @since 1.5
 @since.unbundled 1.0

<!-- END DATA -->
<!-- BEGIN KEY -->
private java.lang.Throwable javax.management.remote.JMXProviderException.cause
<!-- END KEY -->
<!-- BEGIN DATA -->
 @serial An exception that caused this exception to be thrown.
         This field may be null.
 @see #getCause()

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.remote.JMXProviderException()
<!-- END KEY -->
<!-- BEGIN DATA -->
 <p>Constructs a <code>JMXProviderException</code> with no
 specified detail message.</p>

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.remote.JMXProviderException(String message)
<!-- END KEY -->
<!-- BEGIN DATA -->
 <p>Constructs a <code>JMXProviderException</code> with the
 specified detail message.</p>

 @param message the detail message

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.management.remote.JMXProviderException(String message, Throwable cause)
<!-- END KEY -->
<!-- BEGIN DATA -->
 <p>Constructs a <code>JMXProviderException</code> with the
 specified detail message and nested exception.</p>

 @param message the detail message
 @param cause the nested exception

<!-- END DATA -->
